image: ubuntu:18-04

cache:
  paths:
    - vendor/

before_script:
  - whoami
  - wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
  - LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php -y
  - apt update
  - apt install php7.3-fpm php7.3 php7.3-sqlite php7.3-ldap php7.3-mbstring php7.3-xml php7.3-zip php7.3-ssh2 -y
  - rm `pwd`/build_tools/liman_req.sh
  - cd build_tools
  - mkdir -p liman
  - git clone --depth=50 --branch=master https://gitlab.lab/liman/liman.git liman/server
  - git clone --depth=50 --branch=master https://gitlab.lab/liman/sandbox.git liman/sandbox
  - git clone --depth=50 --branch=master https://github.com/liman/webssh.git liman/webssh
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php -r "if (hash_file('sha384', 'composer-setup.php') === '48e3236262b34d30969dca3c37281b3b4bbe3221bda826ac6a9a62d6444cdb0dcd0615698a5cbe587c3f0fe57a54d8f5') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  - php composer-setup.php
  - php7.3 composer.phar install --no-dev -d liman/server
  - rm -rf liman/server/.git
  - rm -rf liman/sandbox/.git
  - rm -rf liman/webssh/.git
  - mv create_deb.sh ../create_deb.sh
  - chmod +x ../create_deb.sh
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y.%m.%d-%s')}
  - sed -i "s/APP_VERSION=Development/APP_VERSION=$TRAVIS_TAG/g" liman/server/.env
  - sed -i "s/APP_DEBUG=true/APP_DEBUG=false/g" liman/server/.env
  - sed -i "s/APP_ENV=local/APP_ENV=production/g" liman/server/.env
job:
  stage: deploy
  script:
    - ../create_deb.sh `cat liman/server/.env | grep "APP_VERSION" | cut -d "=" -f 2`
    - mv `pwd`/../build_tools.deb `pwd`/../liman-`cat liman/server/.env | grep "APP_VERSION" | cut -d "=" -f 2`.deb
    - echo "Done!"

# Run our tests
# If Xdebug was installed you can generate a coverage report and see code coverage metrics.
#test:
#  script:
#    - vendor/bin/phpunit --configuration phpunit.xml --coverage-text --colors=never
