os: linux
language: php
dist: xenial
before_install:
  - sudo wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
  - sudo LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php -y
  - sudo apt install php7.3-fpm php7.3 php7.3-sqlite php7.3-ldap php7.3-mbstring php7.3-xml php7.3-zip php7.3-ssh2 -y
  - rm `pwd`/build_tools/liman_req.sh
  - cd build_tools
  - mkdir -p liman
  - git clone --depth=50 --branch=master https://github.com/mertcelen/liman.git liman/server
  - git clone --depth=50 --branch=master https://github.com/mertcelen/liman-sandbox.git liman/sandbox
  - git clone --depth=50 --branch=master https://github.com/mertcelen/liman-webssh.git liman/webssh
  - composer install --no-dev -d liman/server
  - rm -rf liman/server/.git
  - rm -rf liman/sandbox/.git
  - rm -rf liman/webssh/.git
  - mv create_deb.sh ../create_deb.sh
  - chmod +x ../create_deb.sh
  - git config --local user.name "mertcelen"
  - git config --local user.email "mcelen94@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y.%m.%d-%s')}
  - git tag $TRAVIS_TAG
  - sed -i "s/APP_VERSION=Development/APP_VERSION=$TRAVIS_TAG/g" liman/server/.env
script:
  - ../create_deb.sh `cat liman/server/.env | grep "APP_VERSION" | cut -d "=" -f 2`
  - mv `pwd`/../build_tools.deb `pwd`/../liman-`cat liman/server/.env | grep "APP_VERSION" | cut -d "=" -f 2`.deb
deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file: /home/travis/build/mertcelen/liman/liman-`cat liman/server/.env | grep "APP_VERSION" | cut -d "=" -f 2`.deb
  prerelease: true
  name: Liman Version `cat liman/server/.env | grep "APP_VERSION" | cut -d "=" -f 2`