os: linux
language: php
dist: xenial
before_install:
#  - chmod +x ./build_tools/liman_req.sh
#  - ./build_tools/liman_req.sh
  - rm `pwd`/build_tools/liman_req.sh
  - cd build_tools
  - mkdir liman
  - git clone --depth=50 --branch=master https://github.com/mertcelen/liman.git liman/server
  - git clone --depth=50 --branch=master https://github.com/mertcelen/liman-sandbox.git liman/sandbox
  - chmod +x create_deb.sh
script:
  - ./create_deb.sh `cat ../.env | grep "APP_VERSION" | cut -d "=" -f 2`
  - pwd
  - mv `pwd`/build_tools.deb `pwd`/liman-`cat ../.env | grep "APP_VERSION" | cut -d "=" -f 2`.deb
deploy:
  provider: releases
  api_key: GITHUB_TOKEN
  file: /home/travis/build/mertcelen/liman/build_tools/liman-`cat ../.env | grep "APP_VERSION" | cut -d "=" -f 2`.deb
  skip_cleanup: true
  draft: true