name: Liman CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Getting Main Liman Repository
        uses: actions/checkout@v2
        with:
          path: package/liman/server

      - name: Getting Liman' PHP Sandbox
        uses: actions/checkout@v2
        with:
          repository: limanmys/php-sandbox
          path: package/liman/sandbox/php
          token: ${{ secrets.CI_TOKEN }}
          ref: "1.4-dev"

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Getting Liman' WebSSH
        uses: actions/checkout@v2
        with:
          repository: limanmys/webssh
          path: package/liman/webssh
          token: ${{ secrets.CI_TOKEN }}
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          cd package/liman/server
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Create Docs
        run: |
          sudo apt install npm -y
          cd package/liman/server/
          npm install
          npm run docs
          echo "api.liman.dev" > storage/docs/CNAME
      - name: Set up Liman Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.3"
          tools: composer
          extensions : ssh2, curl, sqlite3, ldap, mbstring, xml, zip, posix, smbclient, mongodb, gd
      - name: Build Liman Package
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt install jq -y 1>/dev/null 2>/dev/null
          VERSION=`cat package/liman/server/storage/VERSION`
          echo $GITHUB_RUN_NUMBER > package/liman/server/storage/VERSION_CODE
          COMMIT="${GITHUB_REF#refs/heads/} : "
          COMMIT+=`git --git-dir=package/liman/server/.git log -1 --pretty=%B`
          COMMIT=`echo $COMMIT | jq -SrR @uri`
          DATE=$(date)
          composer install --no-dev -d package/liman/server
          git --git-dir=package/liman/server/.git log -30 --pretty=format:"%s%x09%ad" > package/liman/server/storage/changelog
          rm -rf package/liman/server/.git package/liman/sandbox/php/.git
          rm -rf package/liman/server/node_modules
          mv package/liman/server/storage/build_tools/DEBIAN package/
          rm -rf package/liman/server/storage/build_tools
          cd package
          touch DEBIAN/md5sums
          touch DEBIAN/md5sums
          touch DEBIAN/control

          find . -type f ! -regex '.*.hg.*' ! -regex '.*?debian-binary.*' ! -regex '.*?DEBIAN.*' -printf '%P ' | xargs md5sum  1>/dev/null 2>/dev/null || true

          chmod 775 DEBIAN/preinst
          chmod 775 DEBIAN/postinst

          echo """Package: liman
          Version: $VERSION-$GITHUB_RUN_NUMBER
          Installed-Size: 77892
          Maintainer: Mert CELEN <mcelen@havelsan.com.tr>
          Section: admin
          Date : $DATE
          Architecture: amd64
          Priority: important
          Description: Liman MYS
          Depends: gpg, zip, unzip, dnsutils, nginx, redis, php-redis, php7.3-fpm, php7.3-curl, php7.3, php7.3-sqlite3, php7.3-ldap, php7.3-snmp, php7.3-mbstring, php7.3-xml, php7.3-zip, php7.3-ssh2, php7.3-posix, libnginx-mod-http-headers-more-filter, php7.3-smbclient, krb5-user, smbclient, libssl1.1, acl, novnc, supervisor, expect, php-mongodb, php7.3-gd, rsyslog, python3.7, python3-jinja2, python3-requests, python3-crypto, python3-paramiko, python3-tornado
          """ > DEBIAN/control
          cd ../
          dpkg-deb -Zgzip --build package
          ls -lah
          [ "$GITHUB_REF" == "refs/heads/master" ] && CHANNEL="liman-release" || CHANNEL="liman-dev-release"
          [ "$GITHUB_REF" == "refs/heads/master" ] && FILE_NAME="liman-$VERSION-$GITHUB_RUN_NUMBER.deb" || FILE_NAME="liman-${GITHUB_REF#refs/heads/}-$VERSION-$GITHUB_RUN_NUMBER.deb"
          curl -F "file=@package.deb" "https://slack.com/api/files.upload?token=$SLACK_TOKEN&channels=$CHANNEL&filename=$FILE_NAME&pretty=1&initial_comment=$COMMIT" || echo
